### ISSUE TITLE
Version Specification

### ISSUE THREAD

**Issue by dempti** [aws-quickstart/quickstart-eks-cdk-python#12]
Hi Team,

I am trying to use this repo to start a development eks cluster for lerning purpose, but I do not seem to find the proper version of cdk that needs to be used for bootstraping this particular repo. Also, a documentation on what the steps should be taken place from the start would be a great help.

**Comment by jasonumiker** [comment]
It works with the most recent version of the CDK which you get the CLI of by running `sudo npm install --upgrade -g aws-cdk` and the associated python components you'll get via `pip install --upgrade -r requirements.txt` in the folder(s) where the templates live.

If you are having versioning issues after running both of those commands then it might have to do with your using python 2 rather than python 3. It is a good point - we may want to change cdk.json to run python3 and the instructions to do the install with pip3 instead of python/pip which might point to python 2 as well as it seems anywhere where there is python3 should also have a symlink from those to the 'right' versions.

We'll try to update the README to be clearer on these points. Thanks for the feedback.

**Comment by dempti** [comment]
Hi @jasonumiker ,

This is weird, but `cdk destroy ` has been stuck for me for more than 1 hour as shown in the snippet below.

![image](https://user-images.githubusercontent.com/87458408/127790905-485c5586-4d3a-4217-93f9-17804ed247c1.png)

The instances, asg, and related has been deleted, however this particular `manifest` as it says is still trying to delete itself.

**Comment by jasonumiker** [comment]
Thanks for the feedback. I've seen that happen once or twice two as well. Since a stack delete is doing the whole cluster that manif but the CF metadata around that Kubernetes manifest seems to have issues with deletion. I wonder if we need a more explicit depends_on to ensure that this manifest is successfully deleted before the cluster or other components that seems to break its ability to clean it up. I'll try to add one.

That said, the whole cluster gets deleted including the manifests and it doesn't seem to hurt anything other than making the deletion take awhile longer and requiring a second manual delete like you mention so I have not been too worried.

**Comment by jasonumiker** [comment]
Can we close this Issue on your original question re: CDK version(s) not working? If so what did that end up being?

**Comment by dempti** [comment]
Hi @jasonumiker yes we can close the issue.
The cdk version I ended up using is 115.0 and have now explicitly implemented on requirements.txt to make sure it does not get updated.
